
import React, { Component } from 'react';
import { StyleSheet, AppState } from 'react-native';

import { Container, Content, Text, View } from 'native-base';
import Modal from 'react-native-modalbox';

import AppNavigator from './AppNavigator';
import ProgressBar from './components/loaders/ProgressBar';

import theme from './themes/base-theme';


var notifications = require('./data/notifications.json');
const timer = require('react-native-timer');
var PushNotification = require('react-native-push-notification');
const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: null,
    height: null,
  },
  modal: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  modal1: {
    height: 300,
  },
});

class App extends Component {

  constructor(props) {
    super(props);
    this.state = {
      showDownloadingModal: false,
      showInstalling: false,
      downloadProgress: 0,
    };
  }

  componentDidMount() {
    this.runNotification();
      this.setState({ showDownloadingModal: false });
 //   AppState.addEventListener('change', this._handleAppStateChange);
  }

  componentWillUnmount() {
 //   AppState.removeEventListener('change', this._handleAppStateChange);
  }

  render() {
    return <AppNavigator />;
  }
    runNotification() {
      PushNotification.localNotificationSchedule({
    id: '1234525', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
    ticker: "Foodsaver", // (optional)
    subText: notifications[Math.floor(Math.random() * notifications.length)  ], // (optional) default: none
    vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
    /* iOS and Android properties */
    title: "Foodsaver", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
    message: "Visste du at…", // (required)
    playSound: false, // (optional) default: true
    
    date: new Date(Date.now() + (172800000)), // in 2 days
    soundName: 'default' // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. });
    });
    }
}

export default App;

PushNotification.configure({

    // (optional) Called when Token is generated (iOS and Android)
    onRegister: function(token) {
        console.log( 'TOKEN:', token );
    },

    // (required) Called when a remote or local notification is opened or received
    onNotification: function(notification) {
        console.log( 'NOTIFICATION:', notification );
    },

    // ANDROID ONLY: GCM Sender ID (optional - not required for local notifications, but is need to receive remote push notifications) 
    senderID: "YOUR GCM SENDER ID",

    // IOS ONLY (optional): default: all - Permissions to register.
    permissions: {
        alert: true,
        badge: true,
        sound: true
    },

    // Should the initial notification be popped automatically
    // default: true
    popInitialNotification: true,

    /**
      * (optional) default: true
      * - Specified if permissions (ios) and token (android and ios) will requested or not,
      * - if not, you must call PushNotificationsHandler.requestPermissions() later
      */
    requestPermissions: true,
});